version: '3.8'

services:
  backend:
    container_name: news_app_backend
    image: news_app_backend
    build: ./backend
    env_file:
      - .env  # This will pass the env vars into the container
    ports:
      - "8000:8000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "ollama serve & 
               sleep 10 && 
               ollama pull mistral && 
               uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    container_name: news_app_frontend
    image: news_app_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules: 